title: <p align="center"> Hrithik Joshi </p>
description:   
  <p align="center"> |
  <a style="color:White;" href="https://www.linkedin.com/in/hrithikjoshi/">LinkedIn</a> |
  <a style="color:White;" href="https://github.com/hrithikjoshi">GitHub</a> |
  
  <br>
  <br>
  Working as a Data Science Trainee at TuringMinds.ai
  <br>
  I have hands-on experience in Python (Numpy, Pandas, Matplotlib, Seaborn)
  MySQL, SQLite, Tableau, R Programming Language (ggplot), Statistics and Probability 
  <br>
  </p>

theme: jekyll-theme-cayman
